const planetContent = [
  { type: null, name: 'Zoukav', description: '' },
  { type: null, name: 'Coderus', description: '' },
  { type: null, name: 'Uzouvis', description: '' },
  { type: null, name: 'Ebrosie', description: '' },
  { type: null, name: 'Uanus', description: '' },
  { type: null, name: 'Muxitera', description: '' },
  { type: null, name: 'Deagantu', description: '' },
  { type: null, name: 'Sorth 3U', description: '' },
  { type: null, name: 'Pharvis I9F4', description: '' },
  { type: null, name: 'Chacitera', description: '' },
  { type: null, name: 'Yucceinus', description: '' },
  { type: null, name: 'Culmoth', description: '' },
  { type: null, name: 'Osonoe', description: '' },
  { type: null, name: 'Jean Pierre', description: '' },
  { type: null, name: 'Voulia', description: '' },
  { type: null, name: 'Grakibos', description: '' },
  { type: null, name: 'Cretilea', description: '' },
  { type: null, name: 'Llypso P948', description: '' },
  { type: null, name: 'Thorix 840', description: '' },
  { type: null, name: 'Rulmapra', description: '' },
  { type: null, name: 'Pochouliv', description: '' },
  { type: null, name: 'Georges tronax', description: '' },
  { type: null, name: 'Obbarvis', description: '' },
  { type: null, name: 'Kalrov', description: '' },
  { type: null, name: 'Teorilia', description: '' },
  { type: null, name: 'Thania', description: '' },
  { type: null, name: 'Llora 9YOJ', description: '' },
  { type: null, name: 'Thilles VF', description: '' },
  { type: null, name: 'Zalranope', description: '' },
  { type: null, name: 'Gondarvis', description: '' },
  { type: null, name: 'Donoe K0', description: '' },
  { type: null, name: 'Drerth 6V7D', description: '' },
  { type: null, name: 'Philippe 22', description: '' },
  { type: null, name: 'Pedro du 92', description: '' },
  { type: null, name: 'Boyubos', description: '' },
  { type: null, name: 'CurryCoco', description: '' },
  { type: null, name: 'Llolla 1SH', description: '' },
  { type: null, name: 'Morue89', description: '' },
  { type: null, name: 'Carth 2L8', description: '' },
  { type: null, name: 'Motherth', description: '' },
  { type: null, name: 'Void Shelter', description: '' },
  { type: null, name: 'Renvaitania', description: '' },
  { type: null, name: 'Ruehiri', description: '' },
  { type: null, name: 'Nounides', description: '' },
  { type: null, name: 'Fissdeup8', description: '' },
  { type: null, name: 'Nade', description: '' },
  { type: null, name: 'Sovagua', description: '' },
  { type: null, name: 'Sapus 1J2', description: '' },
  { type: null, name: 'Cool448d', description: '' },
  { type: null, name: 'ZERGLKZREG', description: '' },
];

export default planetContent;
