const planetContent = [
  {
    type: null,
    name: 'Zoukav',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Coderus',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Uzouvis',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Ebrosie',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Uanus',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Muxitera',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Deagantu',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Sorth 3U',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Pharvis I9F4',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Chacitera',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Yucceinus',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Culmoth',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Osonoe',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Jean Pierre',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Voulia',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Grakibos',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Cretilea',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Llypso P948',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Thorix 840',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Rulmapra',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Pochouliv',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Georges tronax',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Obbarvis',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Kalrov',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Teorilia',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Thania',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Llora 9YOJ',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Thilles VF',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Zalranope',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Gondarvis',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Donoe K0',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Drerth 6V7D',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Philippe 22',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Pedro du 92',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Boyubos',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'CurryCoco',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Llolla 1SH',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Morue89',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Carth 2L8',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Motherth',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Void Shelter',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Renvaitania',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Ruehiri',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Nounides',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Fissdeup8',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Nade',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Sovagua',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Sapus 1J2',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'Cool448d',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    type: null,
    name: 'ZERGLKZREG',
    description: 'This is a pretty nice planet',
    visited: false,
  },
];

export default planetContent;
