const planetContent = [
  {
    id: 0,
    type: null,
    name: 'Zoukav',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 1,
    type: null,
    name: 'Coderus',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 2,
    type: null,
    name: 'Uzouvis',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 3,
    type: null,
    name: 'Ebrosie',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 4,
    type: null,
    name: 'Uanus',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 5,
    type: null,
    name: 'Muxitera',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 6,
    type: null,
    name: 'Deagantu',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 7,
    type: null,
    name: 'Sorth 3U',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 8,
    type: null,
    name: 'Pharvis I9F4',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 9,
    type: null,
    name: 'Chacitera',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 10,
    type: null,
    name: 'Yucceinus',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 11,
    type: null,
    name: 'Culmoth',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 12,
    type: null,
    name: 'Osonoe',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 13,
    type: null,
    name: 'Jean Pierre',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 14,
    type: null,
    name: 'Voulia',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 15,
    type: null,
    name: 'Grakibos',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 16,
    type: null,
    name: 'Cretilea',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 17,
    type: null,
    name: 'Llypso P948',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 18,
    type: null,
    name: 'Thorix 840',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 19,
    type: null,
    name: 'Rulmapra',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 20,
    type: null,
    name: 'Pochouliv',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 21,
    type: null,
    name: 'Georges tronax',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 22,
    type: null,
    name: 'Obbarvis',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 23,
    type: null,
    name: 'Kalrov',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 24,
    type: null,
    name: 'Teorilia',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 25,
    type: null,
    name: 'Thania',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 26,
    type: null,
    name: 'Llora 9YOJ',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 27,
    type: null,
    name: 'Thilles VF',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 27,
    type: null,
    name: 'Zalranope',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 28,
    type: null,
    name: 'Gondarvis',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 29,
    type: null,
    name: 'Donoe K0',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 30,
    type: null,
    name: 'Drerth 6V7D',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 31,
    type: null,
    name: 'Philippe 22',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 32,
    type: null,
    name: 'Pedro du 92',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 33,
    type: null,
    name: 'Boyubos',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 34,
    type: null,
    name: 'CurryCoco',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 35,
    type: null,
    name: 'Llolla 1SH',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 36,
    type: null,
    name: 'Morue89',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 37,
    type: null,
    name: 'Carth 2L8',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 38,
    type: null,
    name: 'Motherth',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 39,
    type: null,
    name: 'Void Shelter',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 40,
    type: null,
    name: 'Renvaitania',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 41,
    type: null,
    name: 'Ruehiri',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 42,
    type: null,
    name: 'Nounides',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 43,
    type: null,
    name: 'Fissdeup8',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 44,
    type: null,
    name: 'Nade',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 45,
    type: null,
    name: 'Sovagua',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 46,
    type: null,
    name: 'Sapus 1J2',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 47,
    type: null,
    name: 'Cool448d',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 48,
    type: null,
    name: 'ZERGLKZREG',
    description: 'This is a pretty nice planet',
    visited: false,
  },
  {
    id: 49,
    type: null,
    name: 'Pepouze',
    description: 'This is a pretty nice planet',
    visited: false,
  },
];

export default planetContent;
